name: stage_colors
description: a set of colors to extend stagexl.
version: 1.0.0
homepage: https://www.txtsme.com
author: spivegin <spivegin@txtsme.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
